#!/bin/bash
r10k=/var/lib/puppet/.gem/ruby/1.8/bin/r10k

while read oldrev newrev refname
do
  branch=${refname#*\/*\/}
  # let r10k take care of everything, all we need is the branch name
  sudo -u puppet $r10k deploy environment $branch -p
  exit=$?
done
exit $exit
